name: CI

on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        npm i
        npx lerna bootstrap
    - name: build
      run: |
        npx lerna run build
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: linting
      run: npx eslint    
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: jest test
      run: npx lerna run test
        
