name: CI

on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        npm run setup --ci
    - name: build
      run: |
        npm run build --ci
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: linting
      run: npm run lint --ci
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: jest test
      run: npm run test --ci --parallel
        
